import { User, BusinessIdea, AIFeedback, Resource, Milestone } from '../types';

export const mockUser: User = {
  id: '1',
  name: 'Explorer',
  email: 'explorer@example.com',
  avatar: 'https://images.pexels.com/photos/1181467/pexels-photo-1181467.jpeg?auto=compress&cs=tinysrgb&w=150&h=150&dpr=2',
  joinDate: '2024-01-15',
};

export const mockIdeas: BusinessIdea[] = [
  {
    id: '1',
    title: 'EcoClean - Sustainable Cleaning Products',
    description: 'A line of environmentally friendly cleaning products made from natural ingredients, targeting eco-conscious consumers.',
    category: 'Consumer Goods',
    submittedAt: '2024-01-20T10:00:00Z',
    status: 'completed',
  },
  {
    id: '2',
    title: 'FitTrack Pro - AI Personal Trainer',
    description: 'Mobile app that uses AI to create personalized workout plans and provide real-time form correction through computer vision.',
    category: 'Health & Fitness',
    submittedAt: '2024-01-18T14:30:00Z',
    status: 'completed',
  },
  {
    id: '3',
    title: 'LocalConnect - Community Marketplace',
    description: 'Platform connecting local service providers with community members for home services, repairs, and maintenance.',
    category: 'Marketplace',
    submittedAt: '2024-01-22T09:15:00Z',
    status: 'analyzing',
  },
];

export const mockFeedback: AIFeedback[] = [
  {
    id: '1',
    ideaId: '1',
    marketScore: 85,
    feasibilityScore: 78,
    competitionScore: 72,
    overallScore: 78,
    strengths: [
      'Growing market demand for eco-friendly products',
      'Clear value proposition for environmentally conscious consumers',
      'Potential for strong brand loyalty',
      'Regulatory support for sustainable products',
    ],
    weaknesses: [
      'Higher production costs than conventional products',
      'Need for extensive ingredient sourcing',
      'Premium pricing may limit market reach',
      'Requires significant marketing to build brand awareness',
    ],
    opportunities: [
      'Partner with eco-friendly retailers',
      'Expand into commercial cleaning market',
      'Develop subscription-based delivery model',
      'Create educational content about sustainability',
    ],
    threats: [
      'Large corporations entering eco-friendly space',
      'Economic downturns affecting premium product sales',
      'Potential greenwashing backlash',
      'Supply chain disruptions for natural ingredients',
    ],
    nextSteps: [
      'Conduct detailed market research on target demographics',
      'Develop minimum viable product with 3-5 core products',
      'Secure sustainable ingredient suppliers',
      'Create brand identity and packaging design',
      'Test products with focus groups',
    ],
    marketAnalysis: {
      demand: 'High and growing - 73% of consumers willing to pay more for sustainable products',
      trends: ['Zero waste movement', 'Plastic-free packaging', 'DIY cleaning solutions', 'Health-conscious living'],
      targetAudience: 'Eco-conscious millennials and Gen Z, household income $50k+, urban and suburban areas',
    },
    competitors: [
      { name: 'Seventh Generation', similarity: 85, differentiation: 'Focus on ultra-natural ingredients' },
      { name: 'Method', similarity: 72, differentiation: 'Premium positioning and design' },
      { name: 'Mrs. Meyer\'s', similarity: 68, differentiation: 'Local ingredient sourcing story' },
    ],
    generatedAt: '2024-01-20T10:30:00Z',
  },
  {
    id: '2',
    ideaId: '2',
    marketScore: 92,
    feasibilityScore: 65,
    competitionScore: 58,
    overallScore: 72,
    strengths: [
      'Large and growing fitness app market',
      'AI technology provides competitive advantage',
      'High user engagement potential',
      'Subscription revenue model',
    ],
    weaknesses: [
      'High technical complexity for computer vision',
      'Requires significant initial investment',
      'User acquisition costs in crowded market',
      'Privacy concerns with video analysis',
    ],
    opportunities: [
      'Partner with gyms and fitness centers',
      'Integrate with wearable devices',
      'Expand to corporate wellness programs',
      'Add nutrition and meal planning features',
    ],
    threats: [
      'Big tech companies with more resources',
      'Privacy regulations affecting video analysis',
      'User retention challenges in fitness apps',
      'Economic impact on discretionary spending',
    ],
    nextSteps: [
      'Develop proof-of-concept for form correction AI',
      'Validate technical feasibility with computer vision experts',
      'Create detailed user experience wireframes',
      'Research data privacy and security requirements',
      'Build MVP with core workout tracking features',
    ],
    marketAnalysis: {
      demand: 'Very high - fitness app market expected to reach $15.6B by 2026',
      trends: ['Home fitness growth', 'AI personalization', 'Wearable integration', 'Virtual personal training'],
      targetAudience: 'Fitness enthusiasts aged 25-45, tech-savvy, income $40k+, urban professionals',
    },
    competitors: [
      { name: 'Nike Training Club', similarity: 65, differentiation: 'AI form correction technology' },
      { name: 'Peloton Digital', similarity: 58, differentiation: 'Focus on technique over group classes' },
      { name: 'Fitbod', similarity: 72, differentiation: 'Real-time visual feedback' },
    ],
    generatedAt: '2024-01-18T15:00:00Z',
  },
];

export const mockResources: Resource[] = [
  {
    id: '1',
    title: 'The Complete Guide to Market Research',
    description: 'Comprehensive guide covering primary and secondary research methods for validating your business idea.',
    category: 'Market Research',
    type: 'article',
    url: '#',
    difficulty: 'beginner',
    estimatedTime: '15 min read',
  },
  {
    id: '2',
    title: 'Building Your First MVP',
    description: 'Step-by-step video tutorial on creating a minimum viable product to test your business concept.',
    category: 'Product Development',
    type: 'video',
    url: '#',
    difficulty: 'intermediate',
    estimatedTime: '45 min watch',
  },
  {
    id: '3',
    title: 'Pitch Deck Template',
    description: 'Professional presentation template used by successful startups to secure funding.',
    category: 'Fundraising',
    type: 'template',
    url: '#',
    difficulty: 'intermediate',
    estimatedTime: '2 hours',
  },
  {
    id: '4',
    title: 'Customer Interview Toolkit',
    description: 'Interactive tool with templates and scripts for conducting effective customer interviews.',
    category: 'Customer Development',
    type: 'tool',
    url: '#',
    difficulty: 'beginner',
    estimatedTime: '30 min setup',
  },
  {
    id: '5',
    title: 'Financial Modeling for Startups',
    description: 'Advanced course on building financial projections and understanding startup metrics.',
    category: 'Finance',
    type: 'video',
    url: '#',
    difficulty: 'advanced',
    estimatedTime: '3 hours',
  },
  {
    id: '6',
    title: 'Digital Marketing Strategy Framework',
    description: 'Comprehensive framework for developing and executing digital marketing campaigns.',
    category: 'Marketing',
    type: 'article',
    url: '#',
    difficulty: 'intermediate',
    estimatedTime: '25 min read',
  },
];

export const mockMilestones: Milestone[] = [
  {
    id: '1',
    title: 'Submit Your First Idea',
    description: 'Get AI-powered feedback on your business concept',
    completed: true,
    completedAt: '2024-01-20T10:00:00Z',
    category: 'Getting Started',
  },
  {
    id: '2',
    title: 'Complete Market Research',
    description: 'Use our research tools to validate market demand',
    completed: true,
    completedAt: '2024-01-21T14:30:00Z',
    category: 'Research',
  },
  {
    id: '3',
    title: 'Define Your MVP',
    description: 'Create a clear plan for your minimum viable product',
    completed: false,
    category: 'Development',
  },
  {
    id: '4',
    title: 'Create Financial Projections',
    description: 'Build realistic financial models for your business',
    completed: false,
    category: 'Finance',
  },
  {
    id: '5',
    title: 'Develop Go-to-Market Strategy',
    description: 'Plan your customer acquisition and marketing approach',
    completed: false,
    category: 'Marketing',
  },
];